### ISSUE TITLE
Problem to restore packages

### ISSUE THREAD

**Issue by OmidID** [jsuarezruiz/xamarin-forms-waveengine-sample#1]
Nice and useful project.
But i have a problem to compile
I don't know what is the problem here. I cannot restore packages
![image](https://user-images.githubusercontent.com/956077/40196806-497e3dec-5a1a-11e8-9c08-fb0717ff4581.png)

**Comment by OmidID** [comment]
I add this myget url `https://www.myget.org/F/waveengine-nightly/api/v3/index.json` and it's worked. now i have this problem. should i do something more?

```

1>------ Build started: Project: XamarinForms3DCarSample, Configuration: Debug Any CPU ------
1>C:\Users\Omid\Downloads\xamarin-forms-waveengine-sample-master\src\packages\WaveEngine.2.5.1-alpha-20180516-645\build\net45\WaveEngine.Common.targets(43,5): error MSB6003: The specified task executable "cmd.exe" could not be run. The working directory "v2.0\Tools\VisualEditor\" does not exist.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by jsuarezruiz** [comment]
Hi, I was not expecting someone to try so fast ;). You need to have the Wave Engine editor installed: [https://waveengine.net](https://waveengine.net)

**Comment by OmidID** [comment]
I have following you because of Xamarin and GTK. We have plan to using Xamarin.Forms with GTK on our controller board.
We doing lot of great thing around 3d in our company that why it's important for me to track this kind of thing. We creating large instrument for factories and currently we using UrhoSharp.
thanks for the answer ;)
